import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { Entry } from '../server/catalog';
import type { Frame, Manifest, State } from '../server/pack';
import './style.css';
type Preview={manifest:Manifest;mapping:Record<State,string>;notes:string[];bytes:number;filename:string;installURL:string};
const labels:Record<State,string>={idle:'Idle',working:'Working',waiting:'Waiting',compacting:'Thinking',error:'Oops',sleep:'Sleeping',celebrate:'Celebrating'};
const directions=['↓ Front','↙ Front left','← Left','↖ Back left','↑ Back','↗ Back right','→ Right','↘ Front right'];
const featured=[570,133,25,1,4,7,94,143,151,155,175,197,258,280,393,448,778];
function Icon({kind}:{kind:'arrow'|'download'|'search'|'pause'|'play'|'close'|'spark'}) {return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='arrow'?<path d="M5 12h14m-5-5 5 5-5 5"/>:kind==='download'?<path d="M12 3v12m-4-4 4 4 4-4M5 16v5h14v-5"/>:kind==='search'?<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>:kind==='pause'?<path d="M9 5v14M15 5v14"/>:kind==='play'?<path d="m8 4 12 8-12 8Z"/>:kind==='close'?<path d="m6 6 12 12M6 18 18 6"/>:<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5Z"/>}</svg>}
function Portrait({entry}:{entry:Entry}) {const [broken,setBroken]=useState(false);useEffect(()=>setBroken(false),[entry.id]);return broken?<span className="portrait-placeholder">✦</span>:<img loading="lazy" width="40" height="40" src={`/api/portrait/${entry.id}`} alt="" onError={()=>setBroken(true)}/>;}
function Sprite({id,direction,frames,paused,sleeping}:{id:string;direction:number;frames:Frame[];paused:boolean;sleeping:boolean}) {
  const canvas=useRef<HTMLCanvasElement>(null);const [error,setError]=useState(false);
  useEffect(()=>{let cancelled=false;let timer:ReturnType<typeof setTimeout>|undefined;let index=0;const images=new Map<string,HTMLImageElement>();setError(false);
    Promise.all([...new Set(frames.map(f=>f.file))].map(file=>new Promise<void>((resolve,reject)=>{const img=new Image();img.onload=()=>{images.set(file,img);resolve();};img.onerror=reject;img.src=`/api/sheets/${id}/${file}?direction=${direction}`;}))).then(()=>{
      if(cancelled)return;
      function draw(){if(cancelled)return;const ctx=canvas.current?.getContext('2d');const f=frames[index];if(ctx&&f){ctx.clearRect(0,0,128,128);ctx.imageSmoothingEnabled=false;ctx.drawImage(images.get(f.file)!,f.x,f.y,f.width,f.height,0,0,128,128);if(!paused){index=(index+1)%frames.length;timer=setTimeout(draw,sleeping?Math.max(1000,f.duration_ms):f.duration_ms);}}}draw();
    }).catch(()=>{if(!cancelled)setError(true);});
    return()=>{cancelled=true;clearTimeout(timer);};
  },[id,direction,frames,paused,sleeping]);
  return error?<p role="alert">Preview couldn’t load. Try another state.</p>:<canvas ref={canvas} width="128" height="128" className="sprite" aria-label="Animated pet preview" role="img"/>;
}
function App(){
  const [entries,setEntries]=useState<Entry[]>([]),[catalogError,setCatalogError]=useState('');
  const [selected,setSelected]=useState('0570'),[query,setQuery]=useState(''),[filter,setFilter]=useState<'favorites'|'all'>('favorites');
  const [direction,setDirection]=useState(1),[state,setState]=useState<State>('idle'),[paused,setPaused]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
  const [preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[install,setInstall]=useState(false),[help,setHelp]=useState(false);
  const [visibleCount,setVisibleCount]=useState(48);
  useEffect(()=>{const controller=new AbortController();fetch('/api/catalog',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('The catalog could not load. Please refresh to retry.');return r.json();}).then(d=>setEntries(d.entries)).catch(e=>{if(e.name!=='AbortError')setCatalogError(e.message);});return()=>controller.abort();},[]);
  useEffect(()=>{setPreview(null);setError('');setInstall(false);const controller=new AbortController();fetch(`/api/preview/${selected}?direction=${direction}`,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(setPreview).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[selected,direction,retry]);
  useEffect(()=>setVisibleCount(48),[query,filter]);
  useEffect(()=>{function close(e:KeyboardEvent){if(e.key==='Escape'){setHelp(false);setInstall(false);}}window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
  const entry=entries.find(e=>e.id===selected);
  const uniqueSpecies=useMemo(()=>{const byNumber=new Map<number,Entry>();for(const e of entries)if(!byNumber.has(e.number)||!e.form)byNumber.set(e.number,e);return [...byNumber.values()];},[entries]);
  const results=uniqueSpecies.filter(e=>query.trim()?`${e.species} ${e.number}`.toLowerCase().includes(query.trim().toLowerCase()):filter==='all'||featured.includes(e.number)).sort((a,b)=>filter==='favorites'&&!query?featured.indexOf(a.number)-featured.indexOf(b.number):a.number-b.number);
  const forms=entries.filter(e=>e.number===entry?.number);
  return <><header className="topbar"><a href="/" className="wordmark"><span className="brand-icon">m<span>✦</span></span>morisoba<span className="wordmark-sub">pets</span></a><nav><span className="small-note">small companions, good company.</span><button className="text-button" onClick={()=>setHelp(true)}>How it works <span>↗</span></button><a className="github" href="https://github.com/sohamb117/omp-pet" target="_blank" rel="noreferrer">OMP Pet ↗</a></nav></header>
  <main><section className="intro"><div><div className="eyebrow"><span className="status-dot"/> THE DESKTOP COMPANION WORKSHOP</div><h1>A little company.<br/><em>A lot of character.</em></h1><p>Pick a Pokémon. Make yourself a desktop friend.<br className="desktop-break"/> It works, waits, and winds down with you.</p></div><div className="intro-note"><span className="hand-star">✳</span><span>for the long builds<br/>and little victories.</span></div></section>
  <section className="workshop" aria-label="Pet builder"><aside className="catalog"><div className="section-heading"><h2><span>01</span> Find your companion</h2><span className="count">{uniqueSpecies.length || '…'} Pokémon</span></div><label className="search"><Icon kind="search"/><input aria-label="Search Pokémon" placeholder="A name or Pokédex number…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><Icon kind="close"/></button>}</label><div className="catalog-tabs"><button aria-pressed={filter==='favorites'} onClick={()=>setFilter('favorites')}>A few favorites</button><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>The whole Pokédex</button></div><div className="pokemon-grid" aria-label="Pokémon choices">{results.slice(0,visibleCount).map(e=><button key={e.id} className={`pokemon ${entry?.number===e.number?'selected':''}`} onClick={()=>{setSelected(e.id);setState('idle');}} aria-pressed={entry?.number===e.number}><span className="dex">#{String(e.number).padStart(3,'0')}</span><Portrait entry={e}/><span className="pokemon-name">{e.species}</span>{entry?.number===e.number&&<span className="selected-dot"/>}</button>)}{catalogError&&<p className="empty" role="alert">{catalogError}</p>}{!entries.length&&!catalogError&&<p className="empty">Opening the Pokédex…</p>}{entries.length>0&&!results.length&&<p className="empty">No companions found.<br/>Try another name or number.</p>}</div>{results.length>visibleCount&&<button className="load-more" onClick={()=>setVisibleCount(n=>n+48)}>Show more companions ↓</button>}<div className="catalog-footer"><span>✦</span> Every good workday deserves a sidekick.</div></aside>
  <div className="builder"><div className="section-heading"><h2><span>02</span> Make it yours</h2><span className="preview-tag">LIVE PREVIEW</span></div><div className="pet-title"><div><span className="eyebrow muted">YOUR NEXT DESKMATE</span><h2>{entry?.species||'Zorua'}<span>#{String(entry?.number||570).padStart(3,'0')}</span></h2></div><span className="pet-seal">made for<br/><b>OMP PET</b></span></div><div className="stage"><div className="stage-top"><span><i/> {labels[state]}</span><button title={paused?'Play animation':'Pause animation'} aria-label={paused?'Play animation':'Pause animation'} onClick={()=>setPaused(!paused)}><Icon kind={paused?'play':'pause'}/></button></div><div className="stage-center">{error?<div className="build-error" role="alert"><p>{error}</p><button onClick={()=>setRetry(n=>n+1)}>Try again</button></div>:preview?<><Sprite id={selected} direction={direction} frames={preview.manifest[state]} paused={paused} sleeping={state==='sleep'}/><span className="pet-shadow"/></>:<div className="loading" role="status"><span>✦</span>Getting your companion ready…</div>}</div><div className="stage-bottom"><span>{state==='sleep'?'Even little companions need a break.':state==='working'?'Keeping you company while things happen.':state==='celebrate'?'A little victory dance. You earned it.':'Looks like you two will get along.'}</span><span className="stage-corner">⌟</span></div></div>
  <div className="state-tabs" aria-label="Animation state">{Object.entries(labels).map(([key,label])=><button key={key} aria-pressed={state===key} onClick={()=>setState(key as State)}>{label}</button>)}</div><div className="selectors"><label>Form<select value={selected} onChange={e=>setSelected(e.target.value)} disabled={!forms.length}>{forms.map(e=><option value={e.id} key={e.id}>{e.form||'Original'}</option>)}</select></label><label>Facing<select value={direction} onChange={e=>setDirection(Number(e.target.value))}>{directions.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label></div><div className="pack-summary"><span><Icon kind="spark"/> Seven moments. One little friend.</span><span>{preview?`${Math.round(preview.bytes/1024)} KB`:'…'}</span></div><div className="actions"><button className="primary" disabled={!preview} onClick={()=>{setInstall(true);window.location.href=preview!.installURL;}}>Adopt in OMP Pet <Icon kind="arrow"/></button><a className={`download ${!preview?'disabled':''}`} aria-disabled={!preview} tabIndex={preview?0:-1} href={preview?`/api/packs/${selected}?direction=${direction}`:undefined} download={preview?.filename}><Icon kind="download"/> Download pack</a></div><p className="install-note">For macOS · OMP Pet 0.1.2+ <button onClick={()=>setHelp(true)}>New here?</button></p>
  <details className="credits"><summary>Made by humans. Meet the sprite artists. <span>+</span></summary><p>{entry?.artists.map((a,i)=><React.Fragment key={a.name}>{i>0?', ':''}{'contact'in a&&a.contact?.startsWith('https://')?<a href={a.contact} target="_blank" rel="noreferrer">{a.name}</a>:a.name}</React.Fragment>)} via <a href="https://sprites.pmdcollab.org/" target="_blank" rel="noreferrer">SpriteCollab</a>.</p><p>All original credits and artwork terms are included in your pack. {preview&&<>Current animation: {preview.mapping[state]}.</>}</p>{preview?.notes.map(n=><p key={n}>{n}</p>)}</details></div></section>
  <section className="bottom-note"><span className="tiny-flower">✳</span><p>Not another thing to look after.<br/><b>Just something nice to have around.</b></p><span>A MORISOBA SIDE QUEST · 2026</span></section></main><footer><span>morisoba <span className="muted">/ a little company</span></span><p>An unofficial, noncommercial fan project. Pokémon belongs to its respective owners.<br/>Sprites from <a href="https://github.com/PMDCollab/SpriteCollab">SpriteCollab</a>, with attribution and <a href="https://github.com/PMDCollab/SpriteCollab/blob/master/LICENSE.md">artwork terms</a> in every pack.</p></footer>
  {(help||install)&&<div className="modal-backdrop" onClick={()=>{setHelp(false);setInstall(false);}}><InstallDialog install={install} url={preview?.installURL} close={()=>{setHelp(false);setInstall(false);}}/></div>}</>;
}
function InstallDialog({install,url,close}:{install:boolean;url?:string;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close();},[]);return <dialog ref={ref} className="modal" onCancel={close} onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Close instructions" onClick={close}><Icon kind="close"/></button><span className="eyebrow">A FRIEND IN A FEW CLICKS</span><h2>{install?'Meet you on the desktop.':'From Pokédex to desktop.'}</h2>{install&&<p>Your browser should ask to open OMP Pet. Allow it to download and activate your selected companion.</p>}<ol><li><b>Get OMP Pet.</b><p>In OMP, run <code>omp plugin install 'github:sohamb117/omp-pet#v0.1.2'</code>, then <code>/reload-plugins</code>. This also selects the version needed for direct adoption.</p></li><li><b>Start your pet.</b><p>If an older pet is running, use <code>/pet quit</code> first. Run <code>/pet show</code>. This installs and opens the native macOS app. Direct adoption needs version 0.1.2 or later.</p></li><li><b>Bring your companion home.</b><p>Choose “Adopt in OMP Pet” and allow the browser to open the app. Or download the ZIP, unzip it, and run <code>/pet sprites /path/to/unzipped-folder</code>.</p></li></ol>{install&&url&&<a className="primary" href={url}>Open OMP Pet again <Icon kind="arrow"/></a>}<p className="modal-footnote">No account. No subscription. Just a little company.</p></dialog>;}
createRoot(document.getElementById('root')!).render(<App/>);
